#pragma once

#define BUTTON_SIZE_WIDTH 180
#define BUTTON_SIZE_HEIGHT 168

#define REPLAY_SIZE_WIDTH 120	
#define REPLAY_SIZE_HEIGHT 45

#define MENU_SIZE_WIDTH 120
#define MENU_SIZE_HEIGHT 45

#define SHOP_SIZE_WIDTH 100
#define SHOP_SIZE_HEIGHT 83

#define ITEM_SIZE_WIDTH 120
#define ITEM_SIZE_HEIGHT 107

#define ITEM_BUTTON_SIZE_WIDTH 120
#define ITEM_BUTTON_SIZE_HEIGHT 21