#pragma once

#define MAX_IMAGE_INDEX 22

#define LINE_FRAME_MOVING_SPEED_EASY 2.5
#define LINE_FRAME_MOVING_SPEED_NORMAL 4
#define LINE_FRAME_MOVING_SPEED_HARD 5.5

#define BALLOON_MOVING_SPEED 1.5
#define BALLOON_MOVING_SPEED_NORMAL 2.5
#define BALLOON_MOVING_SPEED_HARD 4.0

#define EASY_MODE 8
#define NORMAL_MODE 45
#define HARD_MODE 60
#define COMPLETE_LEVEL 80